#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 220
#define FLOW_TAP_TERM 150

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "QlVyg/LvqG0R"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 3

#define RGB_MATRIX_STARTUP_SPD 60

#define VOYAGER_USER_LEDS
#define QUICK_TAP_TERM_PER_KEY
